config/routes.rb
Rails.application.routes.draw do
  resources :beer_tags, only: [:new, :create]
  resources :tags, only:[:new, :create]
  resources :users, except: [:index]
  resources :favorite_beers, only:[:new, :create, :delete, :show]
  resources :retailers
  resources :beers
  resources :breweries
  resources :retailer_beers, only:[:new, :create, :edit, :update]


  get '/login', to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :favorite_beers
	has_many :beers, through: :favorite_beers
	has_one :brewery
	has_one :retailer
	validates :username, presence: true, uniqueness: [case_sensitive: false]
	validates :password_digest, presence: true
	validates :user_type, presence: true
	accepts_nested_attributes_for :brewery
	has_secure_password

	def self.user_types
		["Brewery", "Retailer", "Customer"]
	end 

	# def password=(new_password)
	# 	salt = BCrypt::Engine::generate_salt
	# 	hashed = BCrypt::Engine::hash_secret(new_password, salt)
	# 	self.password_digest = salt + hashed
	# end
	#
	# 	# authenticate(password: string) -> User?
	# def authenticate(password)
	# 	# Salts generated by generate_salt are always 29 chars long.
	# 	salt = password_digest[0..28]
	# 	hashed = BCrypt::Engine::hash_secret(password, salt)
	# 	return nil unless (salt + hashed) == self.password_digest
	# end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# layout "login"
	before_action :find_user, only: [:show, :edit, :update]

	def show
		@retaileruser = User.new
		
		if get_current_user.user_type == "Retailer"
			@retailer = Retailer.new
		end
		if get_current_user.user_type == "Brewery"
			@unclaimed_breweries = Brewery.where(user_id: nil)
			@brewery = Brewery.new
		end

	end

	def new
		if get_current_user
			redirect_to user_path(get_current_user)
		else
			@user = User.new
		end
	end


	def create
		@user = User.new(user_params)
		if @user.valid?
	        @user.save
	        session[:user_id] = @user.id
			redirect_to user_path(@user)
		else
			render :new
		end
	end


	def edit
		if get_current_user.id != @user.id 
			redirect_to user_path(@user)
		end
	end

	def update
		@user.update(user_params)
		if @user.valid?
			redirect_to user_path(@user)
		else
			render :new 
		end 
	end

	private

	def find_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit!
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<% if @user.errors %>
	<% @user.errors.full_messages.each do |message| %>
		<li class="error"><%= message %></li>
	<% end %>
<% end %>

<%=form_for @user do |u| %>
	<div>
	<%= u.label "What is your name?" %>
	<%= u.text_field :name %>
	</div>
	<div>
	<%= u.label "Please type a Username" %>
	<%= u.text_field :username %>
	</div>
	<div>
	<%= u.label "Please type a Password" %>
	<%= u.password_field :password  %>
	</div>
	<%if @user.user_type == nil %>
		<div>
		<%= u.label "What kind of User Are You?" %>
		<%= u.select :user_type, options_for_select(User.user_types), prompt: "Please Choose"  %>
		<div>
	<% end %>
	<%= u.submit%>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render "user" %>

<%= link_to "Back to Home Page", user_path(@user), class: "hyperlink" %>

app/views/users/new.html.erb
<div class="bar" id="account_creation"><h1>Create an Account</h1></div>
<%= render "user" %>

app/views/users/show.html.erb
<h1>Your Profile</h1>

<ul>
	<li>Name: <%= @user.name %></li>
	<li>Username: <%= @user.username %></li>
</ul>

<% if get_current_user.id == @user.id %>
<%= link_to "Edit Profile", edit_user_path(@user), class: "hyperlink" %>
<% end %>

<% if get_current_user.brewery %>
	<div>
		<%= link_to "Manage #{@user.brewery.name}", brewery_path(@user.brewery), class: "hyperlink" %>
	</div>
<% end %>

<% if @user.retailer %>
	<div>
		<%= link_to "Manage #{@user.retailer.name}", retailer_path(@user.retailer), class: "hyperlink" %>
	</div>
<% end %>

<% if !@user.beers.empty? %>
	<h2>My Favorite Beers</h2>
	<ul>
		<% @user.beers.each do |beer| %>
			<li><%= link_to beer.name, beer_path(beer), class: "hyperlink" %></li>
		<% end %>
	</ul>
<% else %>
	<h2> Click <%= link_to "Here", beers_path, class: "hyperlink" %> To Favorite Some Beers! </h2>
<% end %>

<% if get_current_user.user_type == "Retailer" && Retailer.where(user_id: get_current_user.id).empty? %>
<h2> Create Retailer Listing </h2>
<%= render "retailers/retailer" %>
<% end %>

<% if get_current_user.user_type == "Brewery" && Brewery.where(user_id: get_current_user.id).empty? %>
<h2> Create a Brewing Company </h2>
<%= render "breweries/brewery" %>



<% end %>