config/routes.rb
Rails.application.routes.draw do
  resources :beer_tags, only: [:new, :create]
  resources :tags, only:[:new, :create]
  resources :users, except: [:index]
  resources :favorite_beers, only:[:new, :create, :delete, :show]
  resources :retailers
  resources :beers
  resources :breweries
  resources :retailer_beers, only:[:new, :create, :edit, :update]


  get '/login', to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/retailer.rb
class Retailer < ApplicationRecord
	has_many :retailer_beers
	has_many :beers, through: :retailer_beers
	belongs_to :user

	def get_retailer_beers
		RetailerBeer.where(retailer_id: self)
	end

	def get_available_beers
		self.retailer_beers.select do |retailer_beer|
			retailer_beer.available == true 
		end 
	end
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
	before_action :authorized
	before_action :find_retailer, only: [:show, :edit, :update]
	def index
		@retailers = Retailer.all
	end

	def show
		@retailerbeer = RetailerBeer.new
		@breweries = Brewery.all
		@beer = Beer.new
	end

	def new
		@retailer = Retailer.new
	end

	def create
		@retailer = Retailer.create(retailer_params)
		if @retailer.valid?
			redirect_to retailer_path(@retailer)
		else
			render :new
		end
	end

	def edit

	end

	def update
		@retailer.update(retailer_params)
		if @retailer.valid?
			redirect_to retailer_path(@retailer)
		else
			render :edit
		end
	end

	private

	def find_retailer
		@retailer = Retailer.find(params[:id])
	end

	def retailer_params
		params.require(:retailer).permit!
	end
end

app/helpers/retailers_helper.rb
module RetailersHelper

	def user_owns_retailer
		get_current_user.user_type == "Retailer" && @retailer.user_id == get_current_user.id
	end


end

app/views/retailers/_retailer.html.erb
<% if @retailer.errors %>
	<% @retailer.errors.full_messages.each do |message| %>
		<li class="error"><%= message %></li>
	<% end %>
<% end %>

<%= form_for @retailer do |r| %>
	<%= r.hidden_field :user_id, value:get_current_user.id %>
	<div>
	<%= r.label "Retailer Name" %>
	<%= r.text_field :name %>
	</div>
	<div>
	<%= r.label "Your City" %>
	<%= r.text_field :city %>
	</div>
	<div>
	<%= r.label "Your State" %>
	<%= r.select :state, options_for_select(Retailer.us_states), prompt: "Select" %>
	</div>
	<div>
	<%= r.submit %>
	</div>
<% end %>

app/views/retailers/edit.html.erb
<%= render "retailer" %>

<%= link_to "Back to Retailer Page", retailer_path(@retailer), class: "hyperlink" %>

app/views/retailers/index.html.erb
<h1>Retailers List</h1>
<ul>
<% @retailers.each do |retailer| %>
	<li><%= link_to retailer.name, retailer_path(retailer) %></li>
<% end %>
</ul>

app/views/retailers/new.html.erb
<%= render "retailer" %>

app/views/retailers/show.html.erb
<h1><%= @retailer.name%> Information</h1>

<ul>
	<li>Location: <%= @retailer.city %>, <%= @retailer.state %></li>
</ul>

<% if user_owns_retailer %>
<div>
<%=link_to "Edit this Retailer", edit_retailer_path(@retailer), class: "hyperlink" %>
</div>
<div>
<%= link_to "Browse Breweries", breweries_path, class: "hyperlink" %>
</div>
<% end %>

<%#add all beers on tap list for customers to see below%>
<% if !@retailer.get_available_beers.empty? %>
<h2> Beers on Tap </h2>
<div class="allbeers">
	<% @retailer.get_available_beers.each do |b| %>
		<div class="card" id="card"style="width: 18rem;">
	 	<%= image_tag(b.beer.image, class: "card-img-top") if b.beer.image.attached? %>
	  	<div class="card-body">
	    <h5 class="card-title">Name: <%= link_to b.beer.name, beer_path(b.beer) %></h5>
	    <p class="card-text">
				Style: <%= b.beer.style %>
				<p>ABV: <%= b.beer.ABV %>%</p>
				<p><%= number_with_precision(b.retailer_price, precision: 2) %> per <%= b.glass_size %> oz pour </p>
			</p>
	    <div class="btn btn-primary"><%=link_to "Beer Info", beer_path(b.beer), :class => "btn"%></div><br>
	    <% if user_owns_retailer %><%=link_to "Edit Details", edit_retailer_beer_path(b) %> <%end%>
	  </div>
	</div>
<% end %>
</ol>
</div>
<% end %>

<% if user_owns_retailer %>
<h2>Add a new offering</h2>

<div>
<%if @beer.errors %>
	<% @beer.errors.full_messages.each do |message| %>
	 	<li class="error"><%= message %></li>
	 <% end %>
<% end %>
</div><br>

<%= form_for @beer do |b| %>
	<div>
	<%= b.collection_select :brewery_id, Brewery.all, :id, :name, prompt: "Select a Brewery" %>
	</div>
	<div>
	 	<%= b.fields_for :brewery, @beer.build_brewery do |brew| %>
	 	<div>
		<%= brew.label "Brewery Name" %>
		<%= brew.text_field :name %>
		</div>
		<div>
		<%= brew.label "Brewery City" %>
		<%= brew.text_field :city %>
		</div>
		<div>
		<%= brew.label "Brewery State" %>
		<%= brew.select :state, options_for_select(Retailer.us_states), prompt: "Select" %>
		</div>
		<div>
		<%= brew.label "Brewery Description" %>
		<%= brew.text_area :description %>
		</div>
		<div>
		<%= brew.label "Brewery Website" %>
		<%= brew.text_field :website %>
		</div>
		<div>
		<%= brew.label "Year Established" %>
		<%= brew.number_field :established %>
		</div>
		<% end %>
	</div>
	<%=b.hidden_field :retailer_id, value: @retailer.id %>
	<div>
	<%= b.label "Beer Name" %>
	<%= b.text_field :name %>
	</div>
	<div>
	<%= b.label "Style" %>
	<%= b.select :style, grouped_options_for_select(Beer.all_beer_styles), prompt: "Select a Beer Style" %>
	</div>
	<div>
	<%= b.label "ABV" %>
	<%= b.number_field :ABV, step: :any %>
	</div>
	<div>
	<%= b.label "IBU" %>
	<%= b.number_field :IBU %>
	</div>
	<div>
	<%= b.label "Description" %>
	<%= b.text_area :description %>
	</div>
	<%= b.fields_for :retailer_beers, @beer.retailer_beers.build do |rb| %>
		<%= rb.hidden_field :retailer_id, value: @retailer.id %>
		<div>
		<%= rb.label "Your Glass Size" %>
		<%= rb.select :glass_size, options_for_select(Beer.beer_glass_sizes), prompt: "Select a Glass Size" %>
		</div>
		<div>
		<%= rb.label "Your Price" %>
		<%= rb.number_field :retailer_price, step: :any %>
		</div>
		<div>
		<%= rb.label "Number of Barrels" %>
		<%= rb.number_field :number_of_barrels %>
		<div>
		<div>
		<%= rb.label "Available?" %>
		<%= rb.select :available, [['Yes', true], ['No', false]] %>
		</div>
			<% end %>
	<%= b.submit %>
	</div>
<% end %>
<% end %>