config/routes.rb
Rails.application.routes.draw do
  resources :beer_tags, only: [:new, :create]
  resources :tags, only:[:new, :create]
  resources :users, except: [:index]
  resources :favorite_beers, only:[:new, :create, :delete, :show]
  resources :retailers
  resources :beers
  resources :breweries
  resources :retailer_beers, only:[:new, :create, :edit, :update]


  get '/login', to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/beer.rb
class Beer < ApplicationRecord
	belongs_to :brewery
	has_many :retailer_beers
	has_many :retailers, through: :retailer_beers
	has_many :favorite_beers
	has_many :users, through: :favorite_beers
	has_many :beer_tags
	has_many :tags, through: :beer_tags
	has_one_attached :image
	validates :IBU, inclusion: {in: 0..120, message: "must be within 0 and 120"}, allow_nil: true
	accepts_nested_attributes_for :retailer_beers
	accepts_nested_attributes_for :brewery
	accepts_nested_attributes_for :tags

	# def ibu_range?
	# 	self.IBU >= 0 || self.IBU <= 120
	# end

	def self.beer_glass_sizes
		[4, 8, 12, 16, 24]
	end

	def self.all_beer_styles
		[["Bocks",
				["German Bock", "German Doppelbock", "German Eisbock", "German Maibock", "German Weizenbock", "Brown Ales", "American Brown Ale", "English Brown Ale", "English Dark Mild Ale", "German Altbier"]],
		["Dark Ales",
				["American Black Ale", "Belgian Dark Ale", "Belgian Dubbel", "German Roggenbier", "Scottish Ale", "Winter Warmer"]],
		["Dark Lagers",
				["American Amber / Red Lager", "European Dark Lager", "German Märzen / Oktoberfest", "German Rauchbier", "German Schwarzbier", "Munich Dunkel Lager", "Vienna Lager"]],
		["Hybrid Beers",
				["American Cream Ale", "Bière de Champagne / Bière Brut", "Braggot", "California Common / Steam Beer"]],
		["India Pale Ales",
				["American Brut IPA", "American Imperial IPA", "American IPA", "Belgian IPA", "English India Pale Ale (IPA)", "New England IPA"]],
		["Pale Ales",
				["American Amber / Red Ale", "American Blonde Ale", "American Pale Ale (APA)", "Belgian Blonde Ale", "Belgian Pale Ale", "Belgian Saison", "English Bitter", "English Extra Special / Strong Bitter (ESB)", "English Pale Ale", "English Pale Mild Ale", "French Bière de Garde", "German Kölsch", "Irish Red Ale"]],
		["Pilseners and Pale Lagers",
				["American Adjunct Lager", "American Imperial Pilsner", "American Lager", "American Light Lager", "American Malt Liquor", "Bohemian Pilsener", "European Export / Dortmunder", "European Pale Lager", "European Strong Lager", "German Helles", "German Kellerbier / Zwickelbier", "German Pilsner", "Pilsner"]],
		["Porters",
				["American Imperial Porter", "American Porter", "Baltic Porter", "English Porter", "Robust Porter", "Smoke Porter"]],
		["Specialty Beers",
				["Chile Beer", "Finnish Sahti", "Fruit and Field Beer", "Herb and Spice Beer", "Japanese Happoshu", "Japanese Rice Lager", "Low Alcohol Beer", "Pumpkin Beer", "Russian Kvass", "Rye Beer", "Scottish Gruit / Ancient Herbed Ale", "Smoke Beer"]],
		["Stouts",
				["American Imperial Stout", "American Stout", "English Oatmeal Stout", "English Stout", "English Sweet / Milk Stout", "Foreign / Export Stout", "Irish Dry Stout", "Russian Imperial Stout"]],
		["Strong Ales",
				["American Barleywine", "American Imperial Red Ale", "American Strong Ale", "American Wheatwine Ale", "Belgian Quadrupel (Quad)", "Belgian Strong Dark Ale", "Belgian Strong Pale Ale", "Belgian Tripel", "British Barleywine", "English Old Ale", "English Strong Ale", "Scotch Ale / Wee Heavy"]],
		["Wheat Beers",
				["American Dark Wheat Ale", "American Pale Wheat Ale", "Belgian Witbier", "Berliner Weisse", "German Dunkelweizen", "German Hefeweizen", "German Kristalweizen"]],
		["Wild/Sour Beers",
				["American Brett", "American Wild Ale", "Belgian Faro", "Belgian Fruit Lambic", "Belgian Gueuze", "Belgian Lambic", "Flanders Oud Bruin", "Flanders Red Ale", "Leipzig Gose"]]]
			end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
	before_action :authorized
	before_action :find_beer, only: [:show, :edit, :update]

	def index

		if params[:beer_tag_description]
			@tag_desc = params[:beer_tag_description]
			@tags = Tag.all.select {|tag| tag.description == params[:beer_tag_description]}
			@beers = []
			@tags.each do |tag|
				tag.beers.each do |beer|
					@beers << beer
				end
			end
			@beers
		else
			@beers = Beer.all
		end
	end

	def show
		@retailerbeer = RetailerBeer.new
		@beer_tag = BeerTag.new
		@tag = Tag.new
		@favorite_beer = FavoriteBeer.new
	end

	def new
		@beer = Beer.new
	end


	def create

		if params["beer"]["retailer_id"] == nil && params["beer"]["brewery_attributes"] == nil
			@beer = Beer.new(beer_params_without_retailer)
			if @beer.valid?
				@beer.save
				redirect_to beer_path(@beer)
			else
				@brewery = Brewery.find(params["beer"]["brewery_id"])
				render "breweries/show"
			end

		elsif params["beer"]["brewery_attributes"]["name"] == ""
			@beer = Beer.new(beer_params_with_existing_brewery)
			if @beer.valid?
				@beer.save
				@retailer = Retailer.find(params[:beer][:retailer_id])
				redirect_to retailer_path(@retailer)
			else
				 @retailer = Retailer.find(params[:beer][:retailer_id])
 				 render "retailers/show"
			end

		else
			@beer = Beer.create(beer_params_with_new_brewery)

			if @beer.valid?
				@retailer = Retailer.find(params[:beer][:retailer_id])
				redirect_to retailer_path(@retailer)
			else
				render :new
			end
		end
	end

	def edit
	end

	def update
		@beer.update(beer_params_without_retailer)
		if @beer.valid?
			redirect_to beer_path(@beer)
		else
			render :edit
		end
	end

	# def new_retailerbeer
	# 	RetailerBeer.new(beer_id: @beer.id,
	# 							retailer_id: params["beer"]["retailer_id"],
	# 							glass_size: params["beer"]["glass_size"],
	# 							retailer_price: params["beer"]["price"]  )
	# end

	private

	def find_beer
		@beer = Beer.find(params[:id])
	end

	def beer_params_with_existing_brewery
		params.require(:beer).permit(:name, 
									 :style, 
									 :ABV, 
									 :IBU, 
									 :description, 
									 :brewery_id, 
									 :retailer_id, 
									 retailer_beers_attributes:
									 	[:number_of_barrels, 
									 	 :glass_size, 
									 	 :retailer_price, 
									 	 :retailer_id, 
									 	 :available])
	end

	def beer_params_with_new_brewery
		params.require(:beer).permit(:name, :style, :ABV, :IBU, :description, :retailer_id, brewery_attributes: [:name, :city, :state, :description, :established, :website], retailer_beers_attributes:[:number_of_barrels, :glass_size, :retailer_price, :retailer_id, :available])
	end

	def beer_params_without_retailer
		params.require(:beer).permit(:name, :style, :ABV, :IBU, :description, :available, :price, :glass_size, :on_site_purchase, :brewery_id, :image)
	end

end

app/helpers/beers_helper.rb
module BeersHelper

	def user_owns_brewery
		@beer.brewery.user_id == get_current_user.id
	end

	def retailer_doesnt_offer_beer
		get_current_user.user_type == "Retailer" && !get_current_user.retailer.retailer_beers.map do |retailer_beer| retailer_beer.beer.id end.include?(@beer.id)
	end
end

app/views/beers/_beer.html.erb
<% if @beer.errors %>
	<% @beer.errors.full_messages.each do |message| %>
		<li class="error"><%= message %></li>
	<% end %>
<% end %>

<%= form_for @beer do |b| %>
	<div>
	<%= b.label "Beer Name" %>
	<%= b.text_field :name %>
	</div>
	<div>
	<%= b.label "Style" %>
	<%= b.select :style, grouped_options_for_select(Beer.all_beer_styles), prompt: "Select a Beer Style"  %>
	</div>
	<div>
	<%= b.label "ABV" %>
	<%= b.number_field :ABV %>
	</div>
	<div>
	<%= b.label "IBU" %>
	<%= b.number_field :IBU %>
	</div>
	<div>
	<%= b.label "Available?" %>
	<%= b.select :available, [['Yes', true], ['No', false]] %>
	</div>
	<div>
	<%= b.label "Price" %>
	<%= b.number_field :price, step: :any %>
	</div>
	<div>
	<%= b.label "On Site Purchase?" %>
	<%= b.select :on_site_purchase, [['Yes', true], ['No', false]] %>
	</div>
	<div>
	<%= b.label "Glass Size (in ounces)" %>
	<%= b.select :glass_size, options_for_select(Beer.beer_glass_sizes), prompt: "Select a Glass Size" %>
	</div>
	<div>
	<%= b.label "Description" %>
	<%= b.text_area :description %>
	</div>
	<div>
	<%= b.submit %>
	</div>
<% end %>

app/views/beers/edit.html.erb
<h1>Edit this Beer</h1>

<%= render "beer" %>

<%= link_to "Back to Info Page", beer_path(@beer), class: "hyperlink" %>

app/views/beers/index.html.erb
<h1> List of Beers </h1>

<%= form_tag(beers_path, method: :get) do %>
  Select a tag <%= select_tag :beer_tag_description, options_for_select(Tag.get_descriptions)%>
  <%= submit_tag 'Search' %>
<% end %><br>

<% if @tag_desc %>
	<h2>Beers with a <%=@tag_desc %> tag</h2>
<% end %>
<ul>
<% @beers.each do |beer| %>
	<li><%= link_to beer.name, beer_path(beer) %></li>
<% end %>
</ul>

<%= link_to "Clear Filters", beers_path %>

app/views/beers/new.html.erb
<h1>Create a Beer</h1>

<%= render "beer" %>

app/views/beers/show.html.erb
<h1><%= @beer.name %> Information</h1>

<%= image_tag(@beer.image) if @beer.image.attached?%>
<ul>
	<li>Style: <%= @beer.style %></li>
	<li>ABV: <%= number_with_precision(@beer.ABV, precision:2) %></li>
	<li>IBU: <%= number_with_precision(@beer.IBU, precision:2) %></li>
	<li>Price: $<%= number_with_precision(@beer.price, precision:2) %></li>
	<li>Available? <%= @beer.available %></li>
	<li>Availability: <%= @beer.availability %></li>
	<li>On Site Purchase? <%= @beer.on_site_purchase %></li>
	<li>Glass Size: <%= @beer.glass_size %> oz</li>
	<li>Brewery: <%= link_to @beer.brewery.name, brewery_path(@beer.brewery), class: "hyperlink" %></li>
</ul>

<% if !@beer.image.attached? %>
<%= form_for @beer do |b| %>
	<%= b.file_field :image %>
	<%= b.submit "Add Image" %>
<% end %>
<% end %>

<% if @beer.description %>
<div>
<b>Description:</b>
<%= @beer.description %>
</div>
<% end %>

<% if user_owns_brewery %>
	<div>
	<%= link_to "Edit this Beer", edit_beer_path(@beer), class: "hyperlink" %>
	</div>
<% end %>

<% if !@beer.tags.empty? %>
<h2>Tags associated with this beer</h2>
<ul>
	<% @beer.tags.each do |tag| %>
		<li><%= link_to tag.description, beers_path(beer_tag_description: tag.description), class: "hyperlink" %></li>
	<% end %>
</ul>
<% end %>

<% if !@beer.retailers.empty? %>
<h2>Retailers Offering This Beer</h2>

<ul>
	<% @beer.retailers.each do |retailer| %>
		<li><%= link_to retailer.name, retailer_path(retailer), class: "hyperlink" %></li>
	<% end %>
</ul>
<% end %>

<% if retailer_doesnt_offer_beer %>
<h2>Add this beer to my tap list</h2>

<%= form_for @retailerbeer do |rb|
	%>
	<%= rb.hidden_field :beer_id, value: @beer.id %>
	<%= rb.hidden_field :retailer_id, value: get_current_user.retailer.id %>
	<div>
	<%= rb.label "Your Glass Size" %>
	<%= rb.select :glass_size, options_for_select(Beer.beer_glass_sizes), prompt: "Select a Glass Size" %>
	</div>
	<div>
	<%= rb.label "Your Price" %>
	<%= rb.number_field :retailer_price, step: :any %>
	</div>
	<div>
	<%= rb.label "Number of Barrels" %>
	<%= rb.number_field :number_of_barrels %>
	</div>
	<div>
	<%= rb.label "Available?" %>
	<%= rb.select :available, [['Yes', true], ['No', false]] %>
	</div>
	<%= rb.submit "Add To Tap" %>
<% end %>
<% end %>

<% if my_favorite_beer %>
		<h2>Here's what you think</h2>
		<h3>"<%= my_favorite_beer.review if my_favorite_beer.review != "" %>"</h3>

	<% else %>
		<h2>Favorite this Beer</h2>
		<%= form_for @favorite_beer do |f| %>
			<%= f.hidden_field :beer_id, value: @beer.id %>
			<%= f.hidden_field :user_id, value: get_current_user.id %>
			<div>
			<%=	f.label "Add Your Thoughts" %><br>
			<%= f.text_area :review %>
			</div>
			<%= f.submit "Favorite" %>
		<% end %>
	<% end %>

<h4>Add a Tag to this Beer </h4>
<%= form_for @beer_tag do |bt| %>
	<%= bt.collection_select :tag_id, Tag.all, :id, :description, prompt: "Choose an Existing Tag"%>
	<%= bt.hidden_field :beer_id, value: @beer.id %>
	<%= bt.submit "Add Tag" %>
	<% end %>
<h4>OR</h4>

<h4>Create a new tag:</h4>
<div>
<%= form_for @tag do |t| %>
	<%= hidden_field_tag 'beer_id', @beer.id %>
	<%= t.label "Description" %>
	<%= t.text_field :description %>
	<%= t.submit "Add Tag" %>
<% end %>
</div><br>

<div>
<%= link_to "Back to Beer List", beers_path, class: "hyperlink" %>
</div>