config/routes.rb
Rails.application.routes.draw do
  resources :beer_tags, only: [:new, :create]
  resources :tags, only:[:new, :create]
  resources :users, except: [:index]
  resources :favorite_beers, only:[:new, :create, :delete, :show]
  resources :retailers
  resources :beers
  resources :breweries
  resources :retailer_beers, only:[:new, :create, :edit, :update]


  get '/login', to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tap List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'http://www.csszengarden.com/examples/style.css' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= yield (:body_class) %>">
  
    <% if session["user_id"] %>
      <div class="bar">
      <div id="logo">
            <%= image_tag src= "logo.png", :id=> "logo_image"%>
      </div>
      <div class="login_buttons">
      <div class="login_field hover" id="logout">
      <%= link_to "Logout", logout_path, method: "DELETE" %>
      </div>
      <div class="login_field hover" id="home_page">
      <%= link_to "My Profile", user_path(get_current_user) %>
      </div>
      <div class="login_field hover" id="retailer_list">
      <%= link_to "Browse Retailers", retailers_path %>
      </div>
      <div class="login_field hover" id="brewery_list">
      <%= link_to "Browse Breweries", breweries_path %>
      </div>
      <div class="login_field hover" id="beer_list">
      <%= link_to "Browse Beers", beers_path %>
      </div>
    </div>
    </div><br>
    <div class="login_field" id="welcome">Welcome <%= get_current_user.username %></div>
    <% end %>
    <%= yield %>
  </body>


</html>

app/views/layouts/brewery.html.erb
<h1>Welcome</h1>

<%= link_to "Manage My Beers", beers_path %>